import { test, expect } from '@playwright/test'; 

test('Orange HRM Login' , async ({page}) =>{
await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login');
//await expect(page).toHaveTitle(/OrangeHRM/);
const userNameTextBox = page.locator("//input[@name='username']");
await userNameTextBox.click();
await userNameTextBox.type("Admin");
const passwordTextBox =  page.locator("//input[@name='password']");
await passwordTextBox.click();
await passwordTextBox.type("admin123");
const loginBtn = page.locator('//button[@type="submit"]');
await loginBtn.click();
const dashboard = page.locator("//h6[text()='Dashboard']");
expect (await dashboard.isVisible());
console.log('Home Page');
console.log(await dashboard.textContent());
const recruitmentTab = page.locator('//span[text()="Recruitment"]');
expect (await recruitmentTab.isVisible());
recruitmentTab.click();
console.log('Clicked on Recruitment Tab');
const addButton = page.locator('//button[text()=" Add "]');
expect (await addButton.isVisible);
await addButton.scrollIntoViewIfNeeded();
await addButton.click();
console.log("Clicked on Add button");
const userFirstName = page.locator('//input[@name="firstName"]');
await userFirstName.click();
await userFirstName.type("Sample");
const userLastName = page.locator('//input[@name="lastName"]');
await userLastName.type("Test");
const emailTextBox = page.locator('//label[text()="Email"]//following::input[@class="oxd-input oxd-input--active"][1]');
await emailTextBox.type("abc@gmail.com");
const saveButton = page.locator('//button[text()=" Save "]');
await saveButton.click();
const savedMessage = page.locator('(//div[@id="oxd-toaster_1"]//following::p)[1]')
await savedMessage.isVisible();
console.log("Saved Successfully");
const candName= page.locator('//div[contains(text(),"sample  sample")]');
await candName.isVisible();
console.log("Candidate added");
});